export const processedResources = [
  {
    description: "Web design awards",
    context: "Large collection of industry-leading websites.",
    category: ["collection"],
    url: "https://www.cssdesignawards.com",
    title: "CSS Design Awards",
    icon: "/vault/CSS Design Awards/icon.png",
    preview: "/vault/CSS Design Awards/preview.png",
    lastEdited: "2024-04-04T15:05:56.454Z",
  },
  {
    description: "Portfolio of Emil Kowalski Design Engineer & Developer",
    context:
      "Simple and clean example of what a professional portfolio should consist of.",
    category: ["portfolio"],
    url: "https://emilkowal.ski",
    external_links: [
      {
        description:
          "Vault - A selection of useful links, tools, engineers and designers to inspire, learn, and create.",
        context:
          "Valut of resources curated by Emil Kowalski for his animations and web interaction design course.",
        category: ["learning", "curated"],
        url: "https://animations.dev/vault",
        title: "Animations on the web",
        icon: "/vault/Emil Kowalski/Animations on the web/icon.png",
        preview: "/vault/Emil Kowalski/Animations on the web/preview.png",
        lastEdited: "2024-04-04T15:06:02.240Z",
      },
    ],
    title: "Emil Kowalski",
    icon: "/vault/Emil Kowalski/icon.png",
    preview: "/vault/Emil Kowalski/preview.png",
    lastEdited: "2024-04-04T15:06:00.031Z",
  },
  {
    description: "Portfolio of Paco Coursey Design Engineer & Developer",
    context:
      "Simple and clean example of what a professional portfolio should consist of.",
    category: ["portfolio"],
    url: "https://paco.me",
    external_links: [
      {
        description:
          "Curation of interfaces and interactions made by Paco Coursey.",
        category: ["learning", "curated"],
        url: "https://paco.me/craft",
        title: "Craft",
        preview: "/vault/Paco Coursey/Craft/preview.png",
        lastEdited: "2024-04-04T15:06:08.281Z",
        icon: "/vault/Paco Coursey/Craft/icon.png",
      },
      {
        description: "⌘K - Fast, composable, unstyled command menu for React.",
        context: "Command Menu react component library made by Paco Coursey.",
        category: ["component library"],
        url: "https://cmdk.paco.me",
        title: "Fast, composable, unstyled command menu for React — ⌘K",
        preview:
          "/vault/Paco Coursey/Fast, composable, unstyled command menu for React — ⌘K/preview.png",
        lastEdited: "2024-04-04T15:06:11.634Z",
        icon: "/vault/Paco Coursey/Fast, composable, unstyled command menu for React — ⌘K/icon.png",
      },
    ],
    title: "Paco Coursey",
    lastEdited: "2024-04-04T15:06:05.170Z",
    icon: "/vault/Paco Coursey/icon.png",
    preview: "/vault/Paco Coursey/preview.png",
  },
  {
    description: "Collection of cutting edge user interfaces and interactions",
    context: "Large collection of industry-leading interface design.",
    category: ["collection"],
    url: "https://www.interfacefutures.com",
    title: "Interface Futures",
    icon: "/vault/Interface Futures/icon.png",
    preview: "/vault/Interface Futures/preview.png",
    lastEdited: "2024-04-04T15:06:19.656Z",
  },
  {
    description:
      'Experimental laboratory of user interface patterns and interactions that make you think "what the fuck?" in a thought-provoking way.',
    context: "Small curation of ui interactions.",
    category: ["curated"],
    url: "https://uiw.tf",
    title: "uiwtf",
    icon: "/vault/uiwtf/icon.png",
    preview: "/vault/uiwtf/preview.png",
    lastEdited: "2024-04-04T15:06:23.817Z",
  },
  {
    description:
      "Small laboratory of fine UI Website and components designed and built by Mariana Castilho",
    context: "Small curation of react components",
    category: ["curated"],
    url: "https://www.uilabs.dev",
    title: "uilabs",
    icon: "/vault/uilabs/icon.png",
    lastEdited: "2024-04-04T15:06:27.470Z",
    preview: "/vault/uilabs/preview.png",
  },
  {
    description: "Web design catalog with inspiration from across the web",
    context: "Large collection of cutting edge web design",
    category: ["collection"],
    url: "https://www.curated.design",
    title: "Curated Design",
    icon: "/vault/Curated Design/icon.png",
    preview: "/vault/Curated Design/preview.png",
    lastEdited: "2024-04-04T15:06:31.359Z",
  },
  {
    description: "Portfolio of product engineer Alexandru Ţurcanu",
    context:
      "Her open-source experiments and projects sections showcase high quality work with context",
    category: ["portfolio"],
    url: "https://alexandru.so",
    external_links: [
      {
        description: "Projects of Alexandru Ţurcanu",
        context:
          "Hover animations that reveal project previews and historical progression turn early projects into a narrative journey, fitting a professional portfolio. This is particularly beneficial for new developers, highlighting growth when lacking extensive professional experience and polished projects.",
        category: ["learning"],
        url: "https://alexandru.so/projects",
        title: "Projects - Alexandru Ţurcanu",
        icon: "/vault/Alexandru Ţurcanu - Product Engineer/Projects - Alexandru Ţurcanu/icon.png",
        preview:
          "/vault/Alexandru Ţurcanu - Product Engineer/Projects - Alexandru Ţurcanu/preview.png",
        lastEdited: "2024-04-04T15:06:36.851Z",
      },
      {
        description: "Playground of small experiments by Alexandru Ţurcanu",
        context: "Experiments are simple, clean and open-source.",
        category: ["learning"],
        url: "https://alexandru.so/experiments",
        title: "Experiments - Alexandru Ţurcanu",
        icon: "/vault/Alexandru Ţurcanu - Product Engineer/Experiments - Alexandru Ţurcanu/icon.png",
        preview:
          "/vault/Alexandru Ţurcanu - Product Engineer/Experiments - Alexandru Ţurcanu/preview.png",
        lastEdited: "2024-04-04T15:06:39.484Z",
      },
    ],
    title: "Alexandru Ţurcanu - Product Engineer",
    icon: "/vault/Alexandru Ţurcanu - Product Engineer/icon.png",
    lastEdited: "2024-04-04T15:06:34.173Z",
    preview: "/vault/Alexandru Ţurcanu - Product Engineer/preview.png",
  },
  {
    description: "Portfolio of design and development studio Reboot",
    context: "Simple layout with interesting interactions.",
    category: ["portfolio", "design"],
    url: "https://reboot.studio",
    title: "reboot",
    preview: "/vault/reboot/preview.png",
    lastEdited: "2024-04-04T15:06:41.709Z",
    icon: "/vault/reboot/icon.png",
  },
  {
    description: "Portfolio of product designer Jamie Gray",
    context:
      "Simple portfolio filled with informative and well documented interaction design documents.",
    category: ["portfolio", "learning"],
    url: "https://www.jamiegray.net",
    external_links: [
      {
        description: "Inline photos interaction design document by Jamie Gray",
        context:
          "Simple and informative interaction design documents that are well documented and easy to understand.",
        category: ["learning"],
        url: "https://www.jamiegray.net/blog/inline-photos",
        title: "Inline photos - Jamie Gray",
        icon: "/vault/Jamie Gray/Inline photos - Jamie Gray/icon.png",
        preview: "/vault/Jamie Gray/Inline photos - Jamie Gray/preview.png",
        lastEdited: "2024-04-04T15:06:47.914Z",
      },
      {
        description:
          "Reducing Clutter on the Map design document by Jamie Gray",
        context:
          "Design document showcasing the process of reducing clutter on a map. The document is well documented and easy to understand. Shows that quality of work is more important than quantity of work.",
        category: ["learning"],
        url: "https://www.jamiegray.net/blog/saturday-map-clutter",
        title: "Reducing Clutter on the Map - Jamie Gray",
        icon: "/vault/Jamie Gray/Reducing Clutter on the Map - Jamie Gray/icon.png",
        preview:
          "/vault/Jamie Gray/Reducing Clutter on the Map - Jamie Gray/preview.png",
        lastEdited: "2024-04-04T15:06:50.083Z",
      },
    ],
    title: "Jamie Gray",
    icon: "/vault/Jamie Gray/icon.png",
    preview: "/vault/Jamie Gray/preview.png",
    lastEdited: "2024-04-04T15:06:44.736Z",
  },
  {
    description:
      "Functional graphics with rich interactivity and animation using state machines and html canvas, used by cutting edge web companies.",
    category: ["development library"],
    url: "https://rive.app",
    external_links: [
      {
        description: "Interactive Demo Playing Cards with Rive",
        context: "Created with rive by Senior Motion Designer",
        category: ["learning"],
        url: "https://x.com/drawsgood/status/1774045914568540649?s=20",
        title:
          'Drawsgood on X: "Interactive playing card demo in @rive_app https://t.co/FIr1jRo7kb" / X',
        icon: "/vault/Rive/icon.png",
        preview: "/vault/Rive/preview.png",
        lastEdited: "2024-04-04T15:07:00.303Z",
      },
      {
        description: "How Duolingo rebuilt all their characters with Rive",
        context:
          "Rive made Duolingo's files smaller and more performant, while also making lip-syncing possible at scale.",
        category: ["learning"],
        url: "https://blog.duolingo.com/world-character-visemes/",
        title: "How Duolingo Animates Its World Characters",
        icon: "/vault/Rive/How Duolingo Animates Its World Characters/icon.png",
        preview:
          "/vault/Rive/How Duolingo Animates Its World Characters/preview.png",
        lastEdited: "2024-04-04T15:07:03.695Z",
      },
      {
        description: "Figma's new homepage is full of Rive animations",
        context: "Rive animations used in figma's new homepage",
        category: ["learning"],
        url: "https://rive.app/blog/figma-s-new-homepage-is-full-of-rive-animations",
        title: "Figma's new homepage is full of Rive animations",
        icon: "/vault/Rive/Figma's new homepage is full of Rive animations/icon.png",
        preview:
          "/vault/Rive/Figma's new homepage is full of Rive animations/preview.png",
        lastEdited: "2024-04-04T15:07:06.189Z",
      },
    ],
    title: "Rive",
    icon: "/vault/Rive/icon.png",
    preview: "/vault/Rive/preview.png",
    lastEdited: "2024-04-04T15:06:52.484Z",
  },
  {
    description: "Portfolio of designer and developer Rauno Freiberg",
    context:
      "Filled with interesting interactions and animations used by vercel and other cutting edge web companies.",
    category: ["portfolio", "design", "learning"],
    url: "https://rauno.me",
    external_links: [
      {
        description: "Craft - A collection of interfaces and interactions",
        context:
          "Collection of interfaces and interactions made by Rauno Freiberg.",
        category: ["learning", "curated"],
        url: "https://rauno.me/craft",
        title: "Craft",
        preview: "/vault/Rauno Freiberg/Craft/preview.png",
        lastEdited: "2024-04-04T15:07:11.411Z",
        icon: "/vault/Rauno Freiberg/Craft/icon.png",
      },
    ],
    title: "Rauno Freiberg",
    preview: "/vault/Rauno Freiberg/preview.png",
    lastEdited: "2024-04-04T15:07:09.609Z",
    icon: "/vault/Rauno Freiberg/icon.png",
  },
  {
    description: "Copy paste component library for React by Manu Arora",
    context:
      "Open source component library of complex animations and interactions",
    category: ["component library"],
    url: "https://ui.aceternity.com",
    external_links: [
      {
        description: "X - @mannupaaji",
        context: "Creator of Aceternity",
        category: ["portfolio"],
        url: "https://twitter.com/mannupaaji",
        title: "Manu Arora",
        lastEdited: "2024-04-04T15:07:19.198Z",
        icon: "/vault/Aceternity UI/Manu Arora/icon.png",
        preview: "/vault/Aceternity UI/Manu Arora/preview.png",
      },
    ],
    title: "Aceternity UI",
    icon: "/vault/Aceternity UI/icon.png",
    lastEdited: "2024-04-04T15:07:13.845Z",
    preview: "/vault/Aceternity UI/preview.png",
  },
  {
    description: "Portfolio of interface designer Ethan Chng",
    context: "Filled with professional data driven design documents.",
    category: ["portfolio", "learning"],
    url: "https://www.ethanchng.com",
    title: "Ethan Chng Design",
    icon: "/vault/Ethan Chng Design/icon.png",
    preview: "/vault/Ethan Chng Design/preview.png",
    lastEdited: "2024-04-04T15:07:22.307Z",
  },
  {
    description: "Collection of website footer design",
    context: "Large collection of industry-leading website footers.",
    category: ["collection"],
    url: "https://www.footer.design",
    title: "Footer",
    icon: "/vault/Footer/icon.png",
    preview: "/vault/Footer/preview.png",
    lastEdited: "2024-04-04T15:07:24.532Z",
  },
  {
    description: "Collection of darkmode website design",
    context: "Large collection of industry-leading darkmode websites.",
    category: ["collection"],
    url: "https://www.darkmodedesign.com",
    title: "Dark Mode Design",
    icon: "/vault/Dark Mode Design/icon.png",
    preview: "/vault/Dark Mode Design/preview.png",
    lastEdited: "2024-04-04T15:07:26.892Z",
  },
  {
    description: "Collection of website design details that feel like magic",
    context:
      "Personal Favorite curation of small ux/ui interactions which feel special.",
    category: ["curated", "design"],
    url: "https://www.designspells.com",
    title: "Design Spells",
    icon: "/vault/Design Spells/icon.png",
    lastEdited: "2024-04-04T15:07:29.409Z",
    preview: "/vault/Design Spells/preview.png",
  },
  {
    description: "Collection of minimalist website design",
    context: "Large collection of industry-leading minimalist websites.",
    category: ["collection"],
    url: "https://minimal.gallery",
    title: "Minimal Gallery",
    icon: "/vault/Minimal Gallery/icon.png",
    preview: "/vault/Minimal Gallery/preview.png",
    lastEdited: "2024-04-04T15:07:38.501Z",
  },
  {
    description: "Anthropology Magazine",
    context:
      "I like the simple but personal design of this website, the articles feel curated and well written.",
    category: ["design", "learning", "misc"],
    url: "https://www.sapiens.org",
    title: "SAPIENS",
    icon: "/vault/SAPIENS/icon.png",
    preview: "/vault/SAPIENS/preview.png",
    lastEdited: "2024-04-04T15:07:41.185Z",
  },
  {
    description: "Portfolio of design studio OMSE",
    context: "Smooth interactions and animations.",
    category: ["misc"],
    url: "https://www.omse.co",
    title: "OMSE",
    icon: "/vault/OMSE/icon.png",
    lastEdited: "2024-04-04T15:07:43.289Z",
    preview: "/vault/OMSE/preview.png",
  },
  {
    description: "Portfolio of web3 company Avara",
    context: "Super minimalist with smooth interactions and animations.",
    category: ["misc"],
    url: "https://avara.xyz",
    title: "Avara",
    icon: "/vault/Avara/icon.png",
    preview: "/vault/Avara/preview.png",
    lastEdited: "2024-04-04T15:07:45.383Z",
  },
  {
    description: "Portfolio of designer and developer Sang Jin Lee",
    context: "Super minimalist unfinished portfolio",
    category: ["portfolio"],
    title: "Sang Jin Lee",
    icon: "/vault/Sang Jin Lee/icon.png",
    preview: "/vault/Sang Jin Lee/preview.png",
    url: "https://www.sang.design",
    lastEdited: "2024-04-04T15:07:49.354Z",
  },
  {
    description: "Geist Design System and component library for React",
    context:
      "Vercel's design system and component library, industry leading and filled with good design patterns.",
    category: ["component library", "design system"],
    url: "https://vercel.com/geist/introduction",
    title: "Vercel Geist",
    icon: "/vault/Vercel Geist/icon.png",
    preview: "/vault/Vercel Geist/preview.png",
    lastEdited: "2024-04-04T15:07:49.354Z",
    external_links: [
      {
        description: "Geist - Modern and minimalist React UI library",
        context:
          "Documentation for Geist UI, Vercel's design system filled with extra components and developer react hooks.",
        title: "Geist UI",
        category: ["component library"],
        icon: "/vault/Vercel Geist/Geist UI/icon.png",
        preview: "/vault/Vercel Geist/Geist UI/preview.png",
        url: "https://geist-ui.dev/",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
    ],
  },
  {
    description:
      "programmatic MP4 videos using React with server-side rendering and parametrization.",
    context:
      "Open-source library for creating mp4 videos with react, used by vercel for ui and code showcase videos.",
    category: ["development library"],
    url: "https://www.remotion.dev",
    title: "Remotion",
    icon: "/vault/Remotion/icon.png",
    preview: "/vault/Remotion/preview.png",
    lastEdited: "2024-04-04T15:07:49.354Z",
    external_links: [
      {
        description: "Next.js Filesystem Routing with Remotion",
        title: "Next.js Filesystem Routing with Remotion",
        context:
          "X Video from @delba_oliveira, DX at Vercel, explaining filesystem routing with Remotion. Her other newer videos are also made with Remotion and really showcase the power of this tool.",
        category: ["learning"],
        url: "https://twitter.com/delba_oliveira/status/1707439537054535867",
        icon: "/vault/Remotion/Next.js Filesystem Routing with Remotion/icon.png",
        preview:
          "/vault/Remotion/Next.js Filesystem Routing with Remotion/preview.png",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
    ],
  },
  {
    description:
      "Best-in-class Design Systems with components and foundations references from top-tier tech companies and leading UI teams",
    context:
      "Large curated collection of industry-leading design systems. One of the best resources for learning web design.",
    title: "Design Systems Surf",
    category: ["collection", "learning", "design system"],
    url: "https://designsystems.surf",
    icon: "/vault/Design Systems Surf/icon.png",
    preview: "/vault/Design Systems Surf/preview.png",
    lastEdited: "2024-04-04T15:07:49.354Z",
    external_links: [
      {
        description:
          "X account of Ilya Greben, creator of Design Systems Surf.",
        title: "Ilya Greben",
        context: "X account of Ilya Greben, creator of Design Systems Surf.",
        category: ["learning", "design system"],
        url: "Ilya Greben",
        icon: "/vault/Design Systems Surf/Ilya Greben/icon.png",
        preview: "/vault/Design Systems Surf/Ilya Greben/preview.png",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
      {
        description:
          "Component anatomy, states, usage, behavior, and best practices, enriched with practical usage examples.",
        title: "Blueprints",
        context:
          "Comprehensive Design System Blueprints for individual components.",
        category: ["learning", "design system"],
        url: "https://designsystems.surf/blueprints",
        icon: "/vault/Design Systems Surf/Blueprints/icon.png",
        preview: "/vault/Design Systems Surf/Blueprints/preview.png",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
      {
        description:
          "Directory of Accessibility, Color System, Typography, and more design system resources.",
        title: "Directories",
        context: "Collection of Design System Resources",
        category: ["learning", "design system"],
        url: "https://designsystems.surf/directories",
        icon: "/vault/Design Systems Surf/Directories/icon.png",
        preview: "/vault/Design Systems Surf/Directories/preview.png",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
      {
        description:
          "Directory for individual components from industry-leading design systems.",
        title: "Components",
        context: "Search by component type and name",
        category: ["learning", "design system"],
        url: "https://designsystems.surf/components",
        icon: "/vault/Design Systems Surf/Components/icon.png",
        preview: "/vault/Design Systems Surf/Components/preview.png",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
      {
        description: "Directory for industry-leading design systems.",
        title: "Design Systems",
        context: "Featuring design systems from industry-leading companies.",
        category: ["learning", "design system"],
        url: "https://designsystems.surf/design-systems",
        icon: "/vault/Design Systems Surf/Design Systems/icon.png",
        preview: "/vault/Design Systems Surf/Design Systems/preview.png",
        lastEdited: "2024-04-04T15:07:49.354Z",
      },
    ],
  },
  {
    description:
      "Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.",
    category: ["component library", "curated"],
    url: "https://ui.shadcn.com",
    title: "shadcn",
    icon: "/vault/shadcn/icon.png",
    preview: "/vault/shadcn/preview.png",
    lastEdited: "2024-04-04T15:59:45.083Z",
  },
  {
    description:
      "Portfolio of motion illustrator and designer, Justine Soulie.",
    context: "WebGL portfolio with a unique design and interactions.",
    category: ["portfolio", "curated"],
    title: "Justine Soulie",
    url: "https://justinesoulie.fr",
    external_links: [
      {
        description: "Portfolio of WebGL developer Patrick Heng",
        context: "Portfolio of developer who worked on the site.",
        category: ["portfolio"],
        title: "Patrick Heng",
        url: "https://patrickheng.com/about",
        icon: "/vault/Justine Soulie/Patrick Heng/icon.png",
        preview: "/vault/Justine Soulie/Patrick Heng/preview.png",
        lastEdited: "2024-04-04T16:40:57.483Z",
      },
      {
        description:
          "headless page builder for Next.js, Nuxt, and SvelteKit sites.",
        context:
          "CDN used to create the Nuxt and WebGL portfolio of Justine Soulie.",
        category: ["development library"],
        title: "Prismic",
        url: "https://prismic.io",
        icon: "/vault/Justine Soulie/Prismic/icon.png",
        preview: "/vault/Justine Soulie/Prismic/preview.png",
        lastEdited: "2024-04-04T16:41:10.825Z",
      },
    ],
    icon: "/vault/Justine Soulie/icon.png",
    preview: "/vault/Justine Soulie/preview.png",
    lastEdited: "2024-04-04T16:40:43.482Z",
  },
  {
    description:
      "Awwwards is a massive collection of the best websites on the internet, great for inspiration and learning. The website recognizes and promotes the talent and effort of the best developers, designers, and web agencies in the world.",
    category: ["curated", "collection"],
    context: " It's a personal goal to have a site featured on here :3",
    title: "Awwwards",
    url: "https://www.awwwards.com",
    preview: "/vault/Awwwards/preview.png",
    lastEdited: "2024-04-04T17:06:32.174Z",
    icon: "/vault/Awwwards/icon.png",
  },
  {
    url: "https://ilovecreatives.com/",
    description:
      "A one-stop  portal  for multifaceted✹creatives looking to stack their digital skills alongside a good vibes✿ community.",
    context:
      "Find inspiration and creative resources and connect with talented individuals.",
    category: ["collection"],
    title: "ilovecreatives",
    icon: "/vault/ilovecreatives/icon.png",
    preview: "/vault/ilovecreatives/preview.png",
    lastEdited: "2024-04-06T18:18:04.789Z",
  },
  {
    url: "https://www.gregorylalle.com",
    description: "Portfolio of developer and designer Gregory Lalle",
    context:
      "Developer of smooth and interactive content focused portfolios for creatives",
    category: ["portfolio"],
    external_links: [
      {
        url: "https://angusemmerson.com/",
        description:
          "Portfolio of Angus Emmerson, a video editor and creative.",
        context: "A simple and clean portfolio with a focus on video content.",
        category: ["portfolio", "design"],
        title: "Video editor — Angus Emmerson",
        icon: "/vault/Grégory Lallé — Creative developer/Video editor — Angus Emmerson/icon.png",
        preview:
          "/vault/Grégory Lallé — Creative developer/Video editor — Angus Emmerson/preview.png",
        lastEdited: "2024-04-06T18:18:38.662Z",
      },
      {
        url: "https://theud.tv",
        description:
          "Portfolio of Visual Art Director Thibault Remetter, aka Theud.",
        context:
          "Beautiful minimal and interactive gallery-content focused portfolio",
        category: ["portfolio", "design"],
        title: "Productive director & video maker — Theud",
        icon: "/vault/Grégory Lallé — Creative developer/Productive director & video maker — Theud/icon.png",
        preview:
          "/vault/Grégory Lallé — Creative developer/Productive director & video maker — Theud/preview.png",
        lastEdited: "2024-04-06T18:18:59.841Z",
      },
      {
        description:
          "Creative studio & Production representing talents that supports brands in the production of content, artistic direction and with the representation of talented artists.",
        context: "Unique design and smooth animations",
        category: ["agency", "curated"],
        title: "Denise Agency",
        url: "https://denise-agency.com/projects/",
        external_links: [
          {
            url: "https://denise-agency.com/who-is/",
            description:
              "About page for Denise Agency, a creative studio & production.",
            category: ["artist", "photographer", "portfolio"],
            title: "Who is Denise Agency",
            context:
              "Layout and use of subtle color in the 3d layering is nice",
            icon: "/vault/Grégory Lallé — Creative developer/Denise Agency/Who is Denise Agency/icon.png",
            preview:
              "/vault/Grégory Lallé — Creative developer/Denise Agency/Who is Denise Agency/preview.png",
            lastEdited: "2024-04-04T16:19:08.657Z",
          },
          {
            url: "https://denise-agency.com/artist/ben-fourmi/",
            description:
              "Denis Agency - Ben Fourmi Profile | photographer and art director based in Paris.",
            category: ["artist", "photographer", "portfolio"],
            title: "Ben Fourmi",
            context: "Gallery animation and interactions :3",
            icon: "/vault/Grégory Lallé — Creative developer/Denise Agency/Ben Fourmi/icon.png",
            preview:
              "/vault/Grégory Lallé — Creative developer/Denise Agency/Ben Fourmi/preview.png",
            lastEdited: "2024-04-04T16:19:13.878Z",
          },
        ],
        icon: "/vault/Grégory Lallé — Creative developer/Denise Agency/icon.png",
        preview:
          "/vault/Grégory Lallé — Creative developer/Denise Agency/preview.png",
        lastEdited: "2024-04-04T16:19:03.582Z",
      },
    ],
    title: "Grégory Lallé — Creative developer",
    icon: "/vault/Grégory Lallé — Creative developer/icon.png",
    preview: "/vault/Grégory Lallé — Creative developer/preview.png",
    lastEdited: "2024-04-06T18:18:20.916Z",
  },
  {
    url: "https://recharts.org/en-US",
    description:
      "A React components composable charting library built on SVG elements with a lightweight dependency on D3 submodules.",
    context: "Charting library used by OpenAI, taobao, ahrefs among others.",
    category: ["component library"],
    icon: "/vault/Recharts/icon.png",
    preview: "/vault/Recharts/preview.png",
    title: "Recharts",
    lastEdited: "2024-04-07T21:43:41.277Z",
  },
  {
    url: "https://designresourc.es",
    description: "A curated list of design resources",
    context:
      "Curated list of Design Inspiration, Books, Tools, Jobs, Resources, Photos & much more.",
    category: ["curated", "learning"],
    title: "Design Resources",
    icon: "/vault/Design Resources/preview.png",
    preview: "/vault/Design Resources/preview.png",
    lastEdited: "2024-04-12T09:10:11.647Z",
  },
  {
    url: "https://wojtek.im",
    description: "Portfolio of Senior UI Engineer Wojtek Witkowski.",
    context: "Clean interactions and fully fleshed out portfolio.",
    category: ["portfolio"],
    title: "Wojtek Witkowski",
    icon: "/vault/Wojtek Witkowski/icon.png",
    preview: "/vault/Wojtek Witkowski/preview.png",
    lastEdited: "2024-04-12T09:33:01.636Z",
  },
  {
    url: "https://toolfolio.io",
    description: "An ever growing portfolio of tools.",
    context:
      "Contains a collection of design, content creation, startup, ai and web tools.",
    category: ["collection"],
    title: "Toolfolio",
    icon: "/vault/Toolfolio/icon.png",
    preview: "/vault/Toolfolio/preview.png",
    lastEdited: "2024-04-13T04:35:00.575Z",
  },
  {
    url: "https://www.nan.fyi",
    description: "Blog of designer and devloper Nanda Syahrasyad",
    context:
      "Extreamly valuable, informative and interative blog posts of coding patterns, animation and design",
    category: ["portfolio", "design", "learning"],
    title: "Not a Number",
    icon: "/vault/Not a Number/icon.png",
    preview: "/vault/Not a Number/preview.png",
    external_links: [
      {
        url: "https://twitter.com/nandafyi",
        description: "i write about computers and stuff",
        context: "Twitter account of Nanda Syahrasyad",
        category: ["social"],
        title: "nandafyi",
        icon: "/vault/Not a Number/nandafyi/icon.png",
        preview: "/vault/Not a Number/nandafyi/preview.png",
        lastEdited: "2024-04-13T04:52:43.060Z",
      },
    ],
    lastEdited: "2024-04-13T04:52:40.262Z",
  },
  {
    url: "https://virgilabloh.com/free-game/",
    description: "A resource center for brands in their earliest phases",
    context:
      "Founded by Virgil Abloh's Free Game is meant to democritize branding, art and information to and uplift more than a few...",
    category: ["learning", "design"],
    external_links: [
      {
        url: "https://canary---yellow.com/category/lecture/",
        title: "Canary Yellow",
        description: "A collection of lectures and resources by Virgil Abloh",
        context:
          "Converge the fields of arts, craft, and design. Those notions merged with contemporary culture make up his inter-disciplinary practice today; stemming from his last 15 years, which is summarized below.",
        category: ["learning", "design"],
        icon: "/vault/FREE-GAME/Canary Yellow/icon.png",
        preview: "/vault/FREE-GAME/Canary Yellow/preview.png",
        lastEdited: "2024-04-13T05:03:42.130Z",
      },
      {
        url: "https://virgilabloh.com",
        title: "Virgil Abloh",
        description: "A collection of all online resources by Virgil Abloh",
        context:
          "Archives of one of the most influential designers of the 21st century",
        category: ["portfolio", "design", "learning", "archive"],
        icon: "/vault/FREE-GAME/Virgil Abloh/icon.png",
        preview: "/vault/FREE-GAME/Virgil Abloh/preview.png",
        lastEdited: "2024-04-15T19:46:19.947Z",
      },
    ],
    title: "FREE-GAME",
    icon: "/vault/FREE-GAME/icon.png",
    preview: "/vault/FREE-GAME/preview.png",
    lastEdited: "2024-04-13T05:03:14.026Z",
  },
  {
    url: "https://syke.co",
    description: "Portfolio of designer developer Jamie Syke",
    context: "Simple but content rich bento style portfolio",
    title: "Jamie Syke",
    category: ["portfolio"],
    external_links: [
      {
        url: "https://twitter.com/jamiesyke",
        description:
          "Internet designer/founder for 15+ years 🌐 · previous clients: google, bumble, spotify, zoom, meta, and 100+ more!",
        context: "Twitter account of Jamie Syke",
        category: ["social"],
        title: "jamiesyke",
        icon: "/vault/Jamie Syke/jamiesyke/icon.png",
        preview: "/vault/Jamie Syke/jamiesyke/preview.png",
        lastEdited: "2024-04-15T19:46:45.653Z",
      },
    ],
    icon: "/vault/Jamie Syke/icon.png",
    preview: "/vault/Jamie Syke/preview.png",
    lastEdited: "2024-04-15T19:46:32.548Z",
  },
  {
    url: "https://ian.dev",
    description: "Portfolio of Vercel Engineer Ian Jones",
    context: "Minimalist portfolio with a focus on concise projects posts",
    category: ["portfolio"],
    external_links: [
      {
        url: "https://twitter.com/witsdev",
        description:
          "Ian Jones. engineer @vercel. views are my own. currently building http://q.page",
        context: "Twitter account of Ian Jones",
        category: ["social"],
        title: "witsdev",
        icon: "/vault/Ian Jones/witsdev/icon.png",
        preview: "/vault/Ian Jones/witsdev/preview.png",
        lastEdited: "2024-04-15T19:47:11.423Z",
      },
    ],
    title: "Ian Jones",
    icon: "/vault/Ian Jones/icon.png",
    preview: "/vault/Ian Jones/preview.png",
    lastEdited: "2024-04-15T19:46:57.812Z",
  },
];
