export const processedResources = [
  {
    description: "Web design awards",
    context: "Large collection of industry-leading websites.",
    category: ["collection"],
    url: "https://www.cssdesignawards.com",
    title: "CSS Design Awards",
    icon: "/vault/CSS Design Awards/icon.png",
    preview: "/vault/CSS Design Awards/preview.png",
    lastEdited: "2024-04-03T07:38:54.534Z",
  },
  {
    description: "Portfolio of Emil Kowalski Design Engineer & Developer",
    context:
      "Simple and clean example of what a professional portfolio should consist of.",
    category: ["portfolio"],
    url: "https://emilkowal.ski",
    external_links: [
      {
        description:
          "Vault - A selection of useful links, tools, engineers and designers to inspire, learn, and create.",
        context:
          "Valut of resources curated by Emil Kowalski for his animations and web interaction design course.",
        category: ["learning", "curated"],
        url: "https://animations.dev/vault",
        title: "Animations on the web",
        icon: "/vault/Emil Kowalski/Animations on the web/icon.png",
        preview: "/vault/Emil Kowalski/Animations on the web/preview.png",
        lastEdited: "2024-04-03T07:38:59.701Z",
      },
    ],
    title: "Emil Kowalski",
    icon: "/vault/Emil Kowalski/icon.png",
    preview: "/vault/Emil Kowalski/preview.png",
    lastEdited: "2024-04-03T07:38:56.853Z",
  },
  {
    description: "Portfolio of Paco Coursey Design Engineer & Developer",
    context:
      "Simple and clean example of what a professional portfolio should consist of.",
    category: ["portfolio"],
    url: "https://paco.me",
    external_links: [
      {
        description:
          "Curation of interfaces and interactions made by Paco Coursey.",
        category: ["learning", "curated"],
        url: "https://paco.me/craft",
        title: "Craft",
        preview: "/vault/Paco Coursey/Craft/preview.png",
        lastEdited: "2024-04-03T08:08:07.283Z",
        icon: "/vault/Paco Coursey/Craft/icon.png",
      },
      {
        description: "⌘K - Fast, composable, unstyled command menu for React.",
        context: "Command Menu react component library made by Paco Coursey.",
        category: ["component library"],
        url: "https://cmdk.paco.me",
        title: "Fast, composable, unstyled command menu for React — ⌘K",
        preview:
          "/vault/Paco Coursey/Fast, composable, unstyled command menu for React — ⌘K/preview.png",
        lastEdited: "2024-04-03T08:08:09.198Z",
        icon: "/vault/Paco Coursey/Fast, composable, unstyled command menu for React — ⌘K/icon.png",
      },
    ],
    title: "Paco Coursey",
    lastEdited: "2024-04-03T08:08:05.331Z",
    icon: "/vault/Paco Coursey/icon.png",
    preview: "/vault/Paco Coursey/preview.png",
  },
  {
    description: "Collection of cutting edge user interfaces and interactions",
    context: "Large collection of industry-leading interface design.",
    category: ["collection"],
    url: "https://www.interfacefutures.com",
    title: "Interface Futures",
    icon: "/vault/Interface Futures/icon.png",
    preview: "/vault/Interface Futures/preview.png",
    lastEdited: "2024-04-03T08:08:13.147Z",
  },
  {
    description:
      'Experimental laboratory of user interface patterns and interactions that make you think "what the fuck?" in a thought-provoking way.',
    context: "Small curation of ui interactions.",
    category: ["curated"],
    url: "https://uiw.tf",
    title: "uiwtf",
    icon: "/vault/uiwtf/icon.png",
    preview: "/vault/uiwtf/preview.png",
    lastEdited: "2024-04-03T07:39:14.208Z",
  },
  {
    description:
      "Small laboratory of fine UI Website and components designed and built by Mariana Castilho",
    context: "Small curation of react components",
    category: ["curated"],
    url: "https://www.uilabs.dev",
    title: "uilabs",
    icon: "/vault/uilabs/icon.png",
    lastEdited: "2024-04-03T08:08:15.829Z",
    preview: "/vault/uilabs/preview.png",
  },
  {
    description: "Web design catalog with inspiration from across the web",
    context: "Large collection of cutting edge web design",
    category: ["collection"],
    url: "https://www.curated.design",
    title: "Curated Design",
    icon: "/vault/Curated Design/icon.png",
    preview: "/vault/Curated Design/preview.png",
    lastEdited: "2024-04-03T08:08:19.916Z",
  },
  {
    description: "Portfolio of product engineer Alexandru Ţurcanu",
    context:
      "Her open-source experiments and projects sections showcase high quality work with context",
    category: ["portfolio"],
    url: "https://alexandru.so",
    external_links: [
      {
        description: "Projects of Alexandru Ţurcanu",
        context:
          "Hover animations that reveal project previews and historical progression turn early projects into a narrative journey, fitting a professional portfolio. This is particularly beneficial for new developers, highlighting growth when lacking extensive professional experience and polished projects.",
        category: ["learning"],
        url: "https://alexandru.so/projects",
        title: "Projects - Alexandru Ţurcanu",
        icon: "/vault/Alexandru Ţurcanu - Product Engineer/Projects - Alexandru Ţurcanu/icon.png",
        preview:
          "/vault/Alexandru Ţurcanu - Product Engineer/Projects - Alexandru Ţurcanu/preview.png",
        lastEdited: "2024-04-03T07:39:29.953Z",
      },
      {
        description: "Playground of small experiments by Alexandru Ţurcanu",
        context: "Experiments are simple, clean and open-source.",
        category: ["learning"],
        url: "https://alexandru.so/experiments",
        title: "Experiments - Alexandru Ţurcanu",
        icon: "/vault/Alexandru Ţurcanu - Product Engineer/Experiments - Alexandru Ţurcanu/icon.png",
        preview:
          "/vault/Alexandru Ţurcanu - Product Engineer/Experiments - Alexandru Ţurcanu/preview.png",
        lastEdited: "2024-04-03T07:39:33.387Z",
      },
    ],
    title: "Alexandru Ţurcanu - Product Engineer",
    icon: "/vault/Alexandru Ţurcanu - Product Engineer/icon.png",
    lastEdited: "2024-04-03T08:08:24.630Z",
    preview: "/vault/Alexandru Ţurcanu - Product Engineer/preview.png",
  },
  {
    description: "Portfolio of design and development studio Reboot",
    context: "Simple layout with interesting interactions.",
    category: ["portfolio", "design"],
    url: "https://reboot.studio",
    title: "reboot",
    preview: "/vault/reboot/preview.png",
    lastEdited: "2024-04-03T08:08:27.153Z",
    icon: "/vault/reboot/icon.png",
  },
  {
    description: "Portfolio of product designer Jamie Gray",
    context:
      "Simple portfolio filled with informative and well documented interaction design documents.",
    category: ["portfolio", "learning"],
    url: "https://www.jamiegray.net",
    external_links: [
      {
        description: "Inline photos interaction design document by Jamie Gray",
        context:
          "Simple and informative interaction design documents that are well documented and easy to understand.",
        category: ["learning"],
        url: "https://www.jamiegray.net/blog/inline-photos",
        title: "Inline photos - Jamie Gray",
        icon: "/vault/Jamie Gray/Inline photos - Jamie Gray/icon.png",
        preview: "/vault/Jamie Gray/Inline photos - Jamie Gray/preview.png",
        lastEdited: "2024-04-03T08:08:34.592Z",
      },
      {
        description:
          "Reducing Clutter on the Map design document by Jamie Gray",
        context:
          "Design document showcasing the process of reducing clutter on a map. The document is well documented and easy to understand. Shows that quality of work is more important than quantity of work.",
        category: ["learning"],
        url: "https://www.jamiegray.net/blog/saturday-map-clutter",
        title: "Reducing Clutter on the Map - Jamie Gray",
        icon: "/vault/Jamie Gray/Reducing Clutter on the Map - Jamie Gray/icon.png",
        preview:
          "/vault/Jamie Gray/Reducing Clutter on the Map - Jamie Gray/preview.png",
        lastEdited: "2024-04-03T08:08:37.698Z",
      },
    ],
    title: "Jamie Gray",
    icon: "/vault/Jamie Gray/icon.png",
    preview: "/vault/Jamie Gray/preview.png",
    lastEdited: "2024-04-03T08:08:31.168Z",
  },
  {
    description:
      "Functional graphics with rich interactivity and animation using state machines and html canvas, used by cutting edge web companies.",
    category: ["development library"],
    url: "https://rive.app",
    external_links: [
      {
        description: "Interactive Demo Playing Cards with Rive",
        context: "Created with rive by Senior Motion Designer",
        category: ["learning"],
        url: "https://x.com/drawsgood/status/1774045914568540649?s=20",
        title:
          'Drawsgood on X: "Interactive playing card demo in @rive_app https://t.co/FIr1jRo7kb" / X',
        icon: "/vault/Rive/icon.png",
        preview: "/vault/Rive/preview.png",
        lastEdited: "2024-04-03T08:43:55.010Z",
      },
      {
        description: "How Duolingo rebuilt all their characters with Rive",
        context:
          "Rive made Duolingo's files smaller and more performant, while also making lip-syncing possible at scale.",
        category: ["learning"],
        url: "https://blog.duolingo.com/world-character-visemes/",
        title: "How Duolingo Animates Its World Characters",
        icon: "/vault/Rive/How Duolingo Animates Its World Characters/icon.png",
        preview:
          "/vault/Rive/How Duolingo Animates Its World Characters/preview.png",
        lastEdited: "2024-04-03T08:08:55.421Z",
      },
      {
        description: "Figma's new homepage is full of Rive animations",
        context: "Rive animations used in figma's new homepage",
        category: ["learning"],
        url: "https://rive.app/blog/figma-s-new-homepage-is-full-of-rive-animations",
        title: "Figma's new homepage is full of Rive animations",
        icon: "/vault/Rive/Figma's new homepage is full of Rive animations/icon.png",
        preview:
          "/vault/Rive/Figma's new homepage is full of Rive animations/preview.png",
        lastEdited: "2024-04-03T08:08:58.110Z",
      },
    ],
    title: "Rive",
    icon: "/vault/Rive/icon.png",
    preview: "/vault/Rive/preview.png",
    lastEdited: "2024-04-03T08:08:47.496Z",
  },
  {
    description: "Portfolio of designer and developer Rauno Freiberg",
    context:
      "Filled with interesting interactions and animations used by vercel and other cutting edge web companies.",
    category: ["portfolio", "design", "learning"],
    url: "https://rauno.me",
    external_links: [
      {
        description: "Craft - A collection of interfaces and interactions",
        context:
          "Collection of interfaces and interactions made by Rauno Freiberg.",
        category: ["learning", "curated"],
        url: "https://rauno.me/craft",
        title: "Craft",
        preview: "/vault/Rauno Freiberg/Craft/preview.png",
        lastEdited: "2024-04-03T08:09:12.132Z",
        icon: "/vault/Rauno Freiberg/Craft/icon.png",
      },
    ],
    title: "Rauno Freiberg",
    preview: "/vault/Rauno Freiberg/preview.png",
    lastEdited: "2024-04-03T08:09:09.177Z",
    icon: "/vault/Rauno Freiberg/icon.png",
  },
  {
    description: "Copy paste component library for React by Manu Arora",
    context:
      "Open source component library of complex animations and interactions",
    category: ["component library"],
    url: "https://ui.aceternity.com",
    external_links: [
      {
        description: "X - @mannupaaji",
        context: "Creator of Aceternity",
        category: ["portfolio"],
        url: "https://twitter.com/mannupaaji",
        title: "Manu Arora",
        lastEdited: "2024-04-03T08:09:19.642Z",
        icon: "/vault/Aceternity UI/Manu Arora/icon.png",
        preview: "/vault/Aceternity UI/Manu Arora/preview.png",
      },
    ],
    title: "Aceternity UI",
    icon: "/vault/Aceternity UI/icon.png",
    lastEdited: "2024-04-03T08:09:15.369Z",
    preview: "/vault/Aceternity UI/preview.png",
  },
  {
    description: "Portfolio of interface designer Ethan Chng",
    context: "Filled with professional data driven design documents.",
    category: ["portfolio", "learning"],
    url: "https://www.ethanchng.com",
    title: "Ethan Chng Design",
    icon: "/vault/Ethan Chng Design/icon.png",
    preview: "/vault/Ethan Chng Design/preview.png",
    lastEdited: "2024-04-03T08:09:25.827Z",
  },
  {
    description: "Collection of website footer design",
    context: "Large collection of industry-leading website footers.",
    category: ["collection"],
    url: "https://www.footer.design",
    title: "Footer",
    icon: "/vault/Footer/icon.png",
    preview: "/vault/Footer/preview.png",
    lastEdited: "2024-04-03T08:09:29.728Z",
  },
  {
    description: "Collection of darkmode website design",
    context: "Large collection of industry-leading darkmode websites.",
    category: ["collection"],
    url: "https://www.darkmodedesign.com",
    title: "Dark Mode Design",
    icon: "/vault/Dark Mode Design/icon.png",
    preview: "/vault/Dark Mode Design/preview.png",
    lastEdited: "2024-04-03T08:09:33.232Z",
  },
  {
    description: "Collection of website design details that feel like magic",
    context:
      "Personal Favorite curation of small ux/ui interactions which feel special.",
    category: ["curated", "design"],
    url: "https://www.designspells.com",
    title: "Design Spells",
    icon: "/vault/Design Spells/icon.png",
    lastEdited: "2024-04-03T08:09:36.257Z",
    preview: "/vault/Design Spells/preview.png",
  },
  {
    description: "Collection of minimalist website design",
    context: "Large collection of industry-leading minimalist websites.",
    category: ["collection"],
    url: "https://minimal.gallery",
    title: "Minimal Gallery",
    icon: "/vault/Minimal Gallery/icon.png",
    preview: "/vault/Minimal Gallery/preview.png",
    lastEdited: "2024-04-03T08:09:44.664Z",
  },
  {
    description: "Anthropology Magazine",
    context:
      "I like the simple but personal design of this website, the articles feel curated and well written.",
    category: ["design", "learning", "misc"],
    url: "https://www.sapiens.org",
    title: "SAPIENS",
    icon: "/vault/SAPIENS/icon.png",
    preview: "/vault/SAPIENS/preview.png",
    lastEdited: "2024-04-03T08:09:48.566Z",
  },
  {
    description: "Portfolio of design studio OMSE",
    context: "Smooth interactions and animations.",
    category: ["misc"],
    url: "https://www.omse.co",
    title: "OMSE",
    icon: "/vault/OMSE/icon.png",
    lastEdited: "2024-04-03T08:09:51.634Z",
    preview: "/vault/OMSE/preview.png",
  },
  {
    description: "Portfolio of web3 company Avara",
    context: "Super minimalist with smooth interactions and animations.",
    category: ["misc"],
    url: "https://avara.xyz",
    title: "Avara",
    lastEdited: "2024-04-03T08:43:57.653Z",
  },
  {
    description: "Portfolio of designer and developer Sang Jin Lee",
    context: "Super minimalist unfinished portfolio",
    category: ["portfolio"],
    title: "Sang Jin Lee",
    icon: "/vault/Sang Jin Lee/icon.png",
    preview: "/vault/Sang Jin Lee/preview.png",
    url: "https://www.sang.design",
    lastEdited: "2024-04-03T08:09:54.724Z",
  },
];
